name: 'iGEM WikiSync'
description: 'Automatically deploy your iGEM Wiki.'
author: 'Pranav Ballaney'
branding:
  icon: 'upload-cloud'  
  color: 'green'
inputs:
  team:
    description: 'iGEM team name'
    required: true
  source:
    description: 'Directory that contains your iGEM Wiki'
    required: true
    default: 'dist'
  build:
    description: 'Directory that stores your processed wiki before deployment'
    required: true
    default: 'build'

runs:
  using: "composite"
  steps: 
    - name: Install WikiSync
      run: pip install igem-wikisync==1.1.0a0
      shell: bash

    - name: Deploy to iGEM
      run: python ${{ github.action_path }}/wikisync.py
      shell: bash
      env:
        WIKISYNC_TEAM:   ${{ inputs.team }}
        WIKISYNC_SOURCE: ${{ inputs.source }}
        WIKISYNC_BUILD:  ${{ inputs.build }}
        WIKISYNC_POSTER: ${{ inputs.poster }}

    - name: Print Upload Map
      run: cat upload_map.yml
      shell: bash
